language: php

php:
  - 7.1
  - 7.2
env:
  - DB=sqlite

install:
  - composer selfupdate
  - composer install

servics:
  - sqlite

test:
  adapter: sqlite3
  database: ":memory:"
  timeout: 500

script:
  - ./vendor/bin/phpcs -s
  - ./vendor/bin/php-cs-fixer fix --diff --dry-run
  - ./vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/coveralls