<?php

namespace Khall\Chat;

use Illuminate\Support\ServiceProvider;

class ChatServiceProvider extends ServiceProvider
{
    public function boot()
    {
        $this->publishes(
            [
            \dirname(__DIR__) . '/config/khall_chat.php' => config_path('khall_chat.php'),
            ],
            'config'
        );
        $path = '/database/migrations/';

        $this->publishes(
            [
                \dirname(__DIR__) . $path => database_path('/migrations/'),
            ],
            'migrations'
        );

        $this->publishes(
            [
            \dirname(__DIR__) . '/views/' => resource_path('/views/vendor/chat'),
            ]
        );
        $this->loadRoutesFrom(__DIR__ . '/routes.php');
    }

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }
}
